//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.UIF.CONTRALAFT.Web.pages {
	
	
	public partial class seguridadPerfil {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombrePerfil;
		
		protected System.Web.UI.HtmlControls.HtmlTextArea txtDescripcion;
		
		protected System.Web.UI.WebControls.Button btnNuevo;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl idModalInfoServer;
		
		protected System.Web.UI.WebControls.Label lblMensajeOk;
	}
}
