//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBS.UIF.CONTRALAFT.Web.pages {
	
	
	public partial class usuario {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombre;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtDocumento;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtContra;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoEntidad;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoPerfil;
		
		protected System.Web.UI.WebControls.Button btnNuevo;
		
		protected System.Web.UI.HtmlControls.HtmlInputText editNombre;
		
		protected System.Web.UI.HtmlControls.HtmlInputText editDNI;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtEntidad;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtRuc;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.LinkButton userProfile;
	}
}
