//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.GOB.FSD.Web.pages {
	
	
	public partial class parametro {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoParametro;
		
		protected System.Web.UI.WebControls.Button btnLimpiar;
		
		protected System.Web.UI.WebControls.Button btnBuscar;
		
		protected System.Web.UI.WebControls.Button btnParametroValor;
		
		protected System.Web.UI.WebControls.GridView GridView1;
		
		protected System.Web.UI.WebControls.LinkButton Button;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombre;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtDescripcion;
		
		protected System.Web.UI.WebControls.Button btnRegistrarParametro;
		
		protected System.Web.UI.UpdatePanel upModal;
		
		protected System.Web.UI.WebControls.Label lblModalTitleValor;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombreParametro;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombreValor;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtDescripcionValor;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtValor;
		
		protected System.Web.UI.WebControls.Button btnCerrarParametroValor;
		
		protected System.Web.UI.WebControls.Button btnRegistrarParametroValor;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl idModalInfoServer;
		
		protected System.Web.UI.WebControls.Label lblMensajeOk;
	}
}
