//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.GOB.FSD.Web.pages {
	
	
	public partial class parametro {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoParametro;
		
		protected System.Web.UI.WebControls.Button btnBuscar;
		
		protected System.Web.UI.WebControls.GridView GridView1;
	}
}
