INSERT [dbo].[PERFIL] ( [C_DET_NOMBRE], [N_FL_ACTIVO], [C_DET_DETALLE], [C_USU_REGISTRO], [C_USU_MODIFICACION], [D_FEC_REGISTRO], [D_FEC_MODIFICACION]) VALUES (N'admnistrador', 1, N'usuario administrador de la pagina', N'41093973', N'41093973', CAST(N'2020-06-29T00:00:00.000' AS DateTime), CAST(N'2020-06-29T00:00:00.000' AS DateTime))
INSERT [dbo].[PERFIL] ( [C_DET_NOMBRE], [N_FL_ACTIVO], [C_DET_DETALLE], [C_USU_REGISTRO], [C_USU_MODIFICACION], [D_FEC_REGISTRO], [D_FEC_MODIFICACION]) VALUES (N'usuario', 1, N'usuario registrador de la pagina de la pagina', N'41093973', N'41093973', CAST(N'2020-06-29T00:00:00.000' AS DateTime), CAST(N'2020-06-29T00:00:00.000' AS DateTime))

INSERT [dbo].[MENU] ( [N_COD_PADRE], [C_DES_NOMBRE], [C_COD_ICON], [C_NOM_PAGE], [N_FL_ACTIVO]) VALUES ( 0, N'Roles', N'icon-lock-open', N'rol', 1)
INSERT [dbo].[MENU] ( [N_COD_PADRE], [C_DES_NOMBRE], [C_COD_ICON], [C_NOM_PAGE], [N_FL_ACTIVO]) VALUES ( 0, N'Perfil', N'icon-lock-open', N'seguridadPerfil', 1)
INSERT [dbo].[MENU] ( [N_COD_PADRE], [C_DES_NOMBRE], [C_COD_ICON], [C_NOM_PAGE], [N_FL_ACTIVO]) VALUES ( 0, N'Usuario', N'icon-lock-open', N'usuario', 1)
INSERT [dbo].[MENU] ( [N_COD_PADRE], [C_DES_NOMBRE], [C_COD_ICON], [C_NOM_PAGE], [N_FL_ACTIVO]) VALUES ( 0, N'ListadoAccion', N'icon-lock-open', N'listadoAcciones', 1)
INSERT [dbo].[MENU] ( [N_COD_PADRE], [C_DES_NOMBRE], [C_COD_ICON], [C_NOM_PAGE], [N_FL_ACTIVO]) VALUES ( 0, N'IniciarEntidad', N'icon-lock-open', N'iniciarEntidad', 1)

INSERT [dbo].[ROL] ( [C_DES_ROL], [N_FL_ACTIVO], [C_DET_DETALLE]) VALUES ( N'PERFIL', 1, N'INGRESA A LA PAGINA DE PERFIL')
INSERT [dbo].[ROL] ( [C_DES_ROL], [N_FL_ACTIVO], [C_DET_DETALLE]) VALUES ( N'USUARIO', 1, N'INGRESA A LA PAGINA DE USUARIO')
INSERT [dbo].[ROL] ( [C_DES_ROL], [N_FL_ACTIVO], [C_DET_DETALLE]) VALUES ( N'ROL', 1, N'INGRESA A LA PAGINA DE ROL')
INSERT [dbo].[ROL] ( [C_DES_ROL], [N_FL_ACTIVO], [C_DET_DETALLE]) VALUES ( N'LISTADOACCIONES', 1, N'INGRESA A LA PAGINA DE ROL')
INSERT [dbo].[ROL] ( [C_DES_ROL], [N_FL_ACTIVO], [C_DET_DETALLE]) VALUES ( N'INICIARENTIDAD', 1, N'INGRESA A LA PAGINA DE ROL')

INSERT [dbo].[MENUROL] ([N_COD_MENU], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 1, 1)
INSERT [dbo].[MENUROL] ([N_COD_MENU], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (2, 2, 1)
INSERT [dbo].[MENUROL] ([N_COD_MENU], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (3, 3, 1)
INSERT [dbo].[MENUROL] ([N_COD_MENU], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (4, 4, 1)
INSERT [dbo].[MENUROL] ([N_COD_MENU], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (5, 5, 1)

INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 1, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 2, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 3, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 4, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (1, 5, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (2, 1, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (2, 2, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (2, 3, 1)
INSERT [dbo].[PERFILROL] ([N_COD_PERFIL], [N_COD_ROL], [N_FL_ACTIVO]) VALUES (2, 4, 1)


INSERT [dbo].[USUARIO] ( [C_DET_CODIGO], [C_DET_NOMBRE], [N_COD_PERFIL], [N_FL_ACTIVO], [D_FEC_REGISTRO], [C_USU_REGISTRO], [C_DET_CONTRA]) VALUES ( N'41093973', N'usu1',  1, 1, CAST(N'2020-06-21T06:06:30.060' AS DateTime), NULL, N'A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3')
INSERT [dbo].[USUARIO] ( [C_DET_CODIGO], [C_DET_NOMBRE], [N_COD_PERFIL], [N_FL_ACTIVO], [D_FEC_REGISTRO], [C_USU_REGISTRO], [C_DET_CONTRA]) VALUES ( N'40627888', N'usu2',  1, 1, CAST(N'2020-06-21T01:07:17.733' AS DateTime), NULL, N'A665A45920422F9D417E4867EFDC4FB8A04A1F3FFF1FA07E998E86F7F7A27AE3')
