//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.COM.FSD.Web.pages {
	
	
	public partial class preSeleccion {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.DropDownList ddlEntidades;
		
		protected System.Web.UI.WebControls.DropDownList ddlClasificacionRiesgo;
		
		protected System.Web.UI.WebControls.DropDownList ddlPorcentajeOficinas;
		
		protected System.Web.UI.WebControls.DropDownList ddlIndicadorDeudaFSD;
		
		protected System.Web.UI.WebControls.Button btnIniciarPreSeleccion;
		
		protected System.Web.UI.WebControls.Button btnLimpiarPreSeleccion;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl idDivTituloLE;
		
		protected System.Web.UI.WebControls.Button btnEnviarInvitaciones;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl idDivSubTituloLE;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl idDivListaEntidades;
		
		protected System.Web.UI.WebControls.GridView GridView1;
	}
}
