//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE.COM.FSD.Web.pages {
	
	
	public partial class usuario {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.ScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.Button btnNuevoUsuario;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtDocumento;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoPerfil;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtNombre;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtEmail;
		
		protected System.Web.UI.UpdatePanel upEntidad;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divEntidad;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoEntidad;
		
		protected System.Web.UI.WebControls.Button btnNuevo;
		
		protected System.Web.UI.HtmlControls.HtmlInputText DNIedit;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoPerfilEdit;
		
		protected System.Web.UI.HtmlControls.HtmlInputText nombreEdit;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtEmailEdit;
		
		protected System.Web.UI.UpdatePanel upEntidadEdit;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divEntidadEdit;
		
		protected System.Web.UI.WebControls.DropDownList ddlCodigoEntidadEdit;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtEntidad;
		
		protected System.Web.UI.HtmlControls.HtmlInputText txtRuc;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.Button btnInactive;
		
		protected System.Web.UI.WebControls.GridView GridView1;
	}
}
